site_name: Runbook Docs
site_url: https://www.runbook.io/
site_description:
site_favicon: 
theme: readthedocs

pages:
- ['index.md', 'Overview']
- ['quick-start.md', 'Overview', 'Quick Start']
- ['architecture-overview.md', 'Overview', 'Architecture Overview']
- ['install_docker_compose.md', 'Contributing', 'Deploy with Docker Compose']
- ['creating_monitors.md', 'Contributing', 'Creating Monitors']
- ['creating_reactions.md', 'Contributing', 'Creating Reactions']
- ['install.md', 'Installing', 'Basic Installation']
- ['install_docker_compose.md', 'Installing', 'Deploy with Docker Compose']
