## Bridge Configuration
stathat_key: "update_me"
envname: "[Self Hosted]"
dbqueue: dc1queue
sleep: 30
## Redis Config
redis_host: redis
redis_port: 6379
redis_db: 0
redis_password: False
## Rethink Config
rethink_host: rethinkdb
rethink_port: 28015
rethink_authkey: False
rethink_db: "crdb"
## Sink Config
sink_ip: actionbroker
sink_port: 6000
sink_worker_port: 6001
## Events Retention
events_retention: 3888000
## History Retention
history_retention: 18000
## MailChimp
mailchimp_api_key: "update_me"
mailchimp_list_id: "update_me"
mailchimp_api_url: "update_me"
## Logging
use_syslog: False

