## Control Configuration
envname: "[Self Hosted]"
stathat_key: update_me!
control_appname: runbook
sleep: 30 
queue: 30seccheck
zone: zone1
## zMQ
broker_ip: monitorbroker
broker_control_port: 5879
broker_worker_port: 5878
## Redis Config
redis_host: redis
redis_port: 6379
redis_db: 0
redis_password: False
## Logging
use_syslog: False
